### PR TITLE
Check for nil pointer in via header

### PR DESCRIPTION
**Pull request by clintberry**
This is a fix to a nil pointer reference. I put in a default just in case.

### CODE REVIEW

**Comment by DiscoViking** [comment]
Looks good. =D

One small thing:  Could you change the definition of port to use "port :=" instead of "var port" to match the surrounding code?

**Comment by clintberry** [comment]
Absolutely. We love this library. Thanks for your contributions.
My friend/co-worker has been fuzzing the lib with all sorts of stress tests. https://github.com/dvyukov/go-fuzz

**Comment by DiscoViking** [comment]
Awesome, we were just talking about doing some fuzzing the other day!

Please do submit more pull requests. :)

If you don't mind me asking, what are you using gossip for?

**Comment by clintberry** [comment]
The plan is to build a distributed SIP proxy/registrar. I have a simple registrar working, but we are still a ways away from completing the distributed data store, dynamically getting data from external data stores, etc. We will be open sourcing the whole thing for all! Hopefully it will be valuable to people. We are just sick of working and scaling these old SIP systems (kamailiio, freeswitch, etc)

**Comment by StefanKopieczek** [comment]
Sounds exciting! Definitely interested to see how you guys get on. Do keep in touch if you have any questions, and if you get the chance to turn any more of your fixes into pull requests we'd love to take them. 
Great to see that you're getting some use out of gossip — we like it too, but it needs a lot more work before I'll feel satisfied with it :)

**Pull request merged**
