### PR TITLE
Fix bug and Add new Feature

### PR DESCRIPTION
**Pull request by kuun**
* Fixed
 - GenericHeader name is lower case
 - Update Content-Length while updating message body
* Feature
 - Support to add header to front of header list

### CODE REVIEW

**Comment by kuun** [comment]
@StefanKopieczek Is the repo is maintained?

**Comment by StefanKopieczek** [comment]
Hey @kuun, yes it is :) I've been travelling for a few weeks so haven't had a chance to look at this yet. Thanks so much for the contribution though - I should be able to take a proper look tomorrow. Sorry for the long wait!

**Comment by StefanKopieczek** [comment]
All look good, thanks a bunch @kuun ! 

I debated a bit about the Content-Length header change since it's not required for UDP traffic, but it doesn't do any harm and it makes the library more usable - so I think it was the right change.

Cheers for helping out with Gossip!

**Comment by kuun** [comment]
Some sip appliances check 'Content-Length', if 'Content-Length' doesn't match real conent length, the request or response will be rejected.

**Pull request merged**
